version: '3'

services:
  web-app-1:
    container_name: web_app_1
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

  web-app-2:
    container_name: web_app_2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-app-1
      - web-app-2