export { default as ChevronRight } from "./ChevronRight";
export { default as DeliveryBiker } from "./DeliveryBiker";
export { default as DeliveryHelmet } from "./DeliveryHelmet";
export { default as Favorite } from "./Favorite";
export { default as Person } from "./Person";
export { default as Pin } from "./Pin";
export { default as Rating } from "./Rating";
export { default as Search } from "./Search";
export { default as Share } from "./Share";
